### ISSUE TITLE
Throw when user code call process.exit()

### ISSUE THREAD

**Issue by kanongil** [kanongil/exiting#2]
The current approach assumes that whatever user code calls `process.exit()` immediately returns. Maybe it would be better to throw a custom error to attempt to escape the calling function?

Failing example:
```js
process.exit(0);
while (true) {}
```

**Comment by ferrao** [comment]
Regarding `process.exit()` the documentation says:

> You should avoid using process.exit() in your own code, and call manager.stop() instead.

But when testing, lab calls process.exit, which is leaving me with a `TypeError: process.exit() was called`. What is the proper way to handle testing then?

**Comment by kanongil** [comment]
You need to ensure that the manager has been stopped before this happens.

**Comment by ferrao** [comment]
I was actually doing something different, was calling `reset` on the manager before each test and getting away with it. 

But my troubles started when I run some tests that call `Inert` route handlers. As soon as I use the response object on the test verifications, I am left with a `UnhandledPromiseRejectionWarning` that traces back to the `process.exit()`.

I am trying to get my head around which exactly is the promise that is not catched.. Of course, all of this goes away if I stop my manager after each test... which might also fail, if the test in question does not start the manager successfully..
