### ISSUE TITLE
Manage multiple servers

### ISSUE THREAD

**Issue by ferrao** [kanongil/exiting#7]
Current implementation allows for managing only one single server instance.

I believe this implementation does not play well with [Hapi v17](https://github.com/hapijs/hapi/issues/3658), which does not accept multiple connections anymore and requires multiple hapi servers to be instantiated.

**Comment by ferrao** [comment]
@kanongil If you agree on this and can provide some guidance I am available for helping you out

**Comment by kanongil** [comment]
Sorry about the slow response – I will take a look at this very soon, as I need it for one of my own servers :-)
